from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Union


Line = Union[str, "ModEntry"]


@dataclass
class ModEntry:
    name: str
    enabled: bool = True
    marker: str = "+"

    @property
    def foreign(self) -> bool:
        return self.marker == "*"

    def render(self) -> str:
        return f"{self.marker}{self.name}"


@dataclass
class PluginEntry:
    name: str
    enabled: bool = False

    def render(self) -> str:
        return f"*{self.name}" if self.enabled else self.name


def _text(path: Path) -> str:
    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8-sig", errors="replace")


def _same(left: str, right: str) -> bool:
    return left.casefold() == right.casefold()


class ModList:
    def __init__(self, lines: list[Line] | None = None):
        self.lines = lines or []

    @classmethod
    def read(cls, path: Path) -> "ModList":
        lines: list[Line] = []
        for raw in _text(path).splitlines():
            stripped = raw.strip()
            if not stripped or stripped.startswith("#"):
                lines.append(raw)
                continue
            marker = stripped[0] if stripped[0] in "+-*" else "+"
            name = stripped[1:].strip() if marker != "+" or stripped[0] in "+-*" else stripped
            if name:
                lines.append(ModEntry(name=name, enabled=marker != "-", marker=marker))
            else:
                lines.append(raw)
        return cls(lines)

    @property
    def entries(self) -> list[ModEntry]:
        return [line for line in self.lines if isinstance(line, ModEntry)]

    def find(self, name: str) -> ModEntry | None:
        return next((entry for entry in self.entries if _same(entry.name, name)), None)

    def set_enabled(self, name: str, enabled: bool) -> ModEntry:
        entry = self.find(name)
        if entry is None:
            raise KeyError(name)
        entry.enabled = enabled
        if not entry.foreign:
            entry.marker = "+" if enabled else "-"
        return entry

    def rename(self, old: str, new: str) -> ModEntry:
        entry = self.find(old)
        if entry is None:
            raise KeyError(old)
        entry.name = new
        return entry

    def add(self, name: str, enabled: bool = True) -> ModEntry:
        if self.find(name) is not None:
            raise KeyError(name)
        entry = ModEntry(name=name, enabled=enabled, marker="+" if enabled else "-")
        self.lines.append(entry)
        return entry

    def move(self, name: str, target: int) -> None:
        entries = self.entries
        current = next((i for i, entry in enumerate(entries) if _same(entry.name, name)), None)
        if current is None:
            raise KeyError(name)
        if target < 0 or target >= len(entries):
            raise IndexError(target)
        entry = entries.pop(current)
        entries.insert(target, entry)
        iterator = iter(entries)
        self.lines = [next(iterator) if isinstance(line, ModEntry) else line for line in self.lines]

    def move_ui(self, name: str, target: int) -> None:
        """Move a mod using the order shown in MO2's left panel.

        MO2 stores modlist.txt in reverse of the visible priority order.
        """
        count = len(self.entries)
        if target < 0 or target >= count:
            raise IndexError(target)
        self.move(name, count - 1 - target)

    def render(self) -> str:
        body = [line if isinstance(line, str) else line.render() for line in self.lines]
        if not body:
            body = ["# This file was automatically generated by Mod Organizer."]
        return "\r\n".join(body) + "\r\n"


class PluginList:
    def __init__(self, lines: list[str | PluginEntry] | None = None):
        self.lines = lines or []

    @classmethod
    def read(cls, path: Path) -> "PluginList":
        lines: list[str | PluginEntry] = []
        for raw in _text(path).splitlines():
            stripped = raw.strip()
            if not stripped or stripped.startswith("#"):
                lines.append(raw)
                continue
            enabled = stripped.startswith("*")
            name = stripped[1:].strip() if enabled else stripped
            if name:
                lines.append(PluginEntry(name, enabled))
            else:
                lines.append(raw)
        return cls(lines)

    @property
    def entries(self) -> list[PluginEntry]:
        return [line for line in self.lines if isinstance(line, PluginEntry)]

    def find(self, name: str) -> PluginEntry | None:
        return next((entry for entry in self.entries if _same(entry.name, name)), None)

    def set_enabled(self, name: str, enabled: bool) -> PluginEntry:
        entry = self.find(name)
        if entry is None:
            raise KeyError(name)
        entry.enabled = enabled
        return entry

    def remove(self, name: str) -> bool:
        wanted = name.casefold()
        before = len(self.entries)
        self.lines = [line for line in self.lines if not isinstance(line, PluginEntry) or line.name.casefold() != wanted]
        return len(self.entries) != before

    def move(self, name: str, target: int) -> None:
        entries = self.entries
        current = next((i for i, entry in enumerate(entries) if _same(entry.name, name)), None)
        if current is None:
            raise KeyError(name)
        if target < 0 or target >= len(entries):
            raise IndexError(target)
        entry = entries.pop(current)
        entries.insert(target, entry)
        iterator = iter(entries)
        self.lines = [next(iterator) if isinstance(line, PluginEntry) else line for line in self.lines]

    def render(self) -> str:
        body = [line if isinstance(line, str) else line.render() for line in self.lines]
        return "\r\n".join(body) + ("\r\n" if body else "")


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + ".mo2cli-tmp")
    temporary.write_text(content, encoding="utf-8", newline="")
    temporary.replace(path)
