from __future__ import annotations

from pathlib import Path

from .formats import write_text
from .workspace import Mo2Error, _safe_name


def initialize(path: str | Path, game_name: str, game_path: str | Path, profile: str = "Default", force: bool = False) -> dict[str, object]:
    root = Path(path).expanduser().resolve()
    _safe_name(profile)
    if root.exists() and any(root.iterdir()) and not force:
        raise Mo2Error(f"Instance directory is not empty; use --force to proceed: {root}")
    root.mkdir(parents=True, exist_ok=True)
    for directory in ("mods", "profiles", "downloads", "overwrite"):
        (root / directory).mkdir(parents=True, exist_ok=True)
    profile_dir = root / "profiles" / profile
    profile_dir.mkdir(parents=True, exist_ok=True)
    write_text(profile_dir / "modlist.txt", "# This file was automatically generated by Mod Organizer.\r\n")
    for filename in ("archives.txt", "plugins.txt", "loadorder.txt"):
        if not (profile_dir / filename).exists():
            write_text(profile_dir / filename, "")
    game = Path(game_path).expanduser().resolve()
    ini = "\r\n".join([
        "[General]",
        f"gameName={game_name}",
        f"gamePath={game}",
        f"selected_profile={profile}",
        "",
        "[Settings]",
        "base_directory=%BASE_DIR%",
        "mod_directory=%BASE_DIR%/mods",
        "profiles_directory=%BASE_DIR%/profiles",
        "download_directory=%BASE_DIR%/downloads",
        "overwrite_directory=%BASE_DIR%/overwrite",
        "",
    ])
    write_text(root / "ModOrganizer.ini", ini)
    return {"instance": str(root), "game": game_name, "game_path": str(game), "profile": profile}
